### ISSUE TITLE
Respecting "decisions" design tokens

### ISSUE THREAD

**Issue by florian-sanders-cc** [CleverCloud/clever-components#506]
# Context 

I just realized that for convenience, I broke the theme system by setting the `cc-badge` text color using the background color Design token:
```css
:host([intent="info"]) {
  --accent-color: var(--cc-color-bg-primary);
}

:host([weight="outlined"]) {
  ...
  color: var(--accent-color, #777);
}
```

This is very convenient and it works because both our "decisions" (`--cc-color-text-success` and `--cc-color-bg-success`) rely on the same color at the moment.

However, this is not a given. 
One could select a different color for text and background in their theme (for instance, this is what Shopify do in [Polaris](https://polaris.shopify.com/tokens/colors) with `surface-success` vs `text-success`).

This will also apply to borders once we introduce border design tokens.

# Solution:

We might need to be less smart and a bit more verbose:
```css
:host([intent="info"]) {
  --bg-color: var(--cc-color-bg-primary);
  --text-color: var(--cc-color-text-primary);
}

:host([weight="outlined"]) {
  ...
  color: var(--text-color, #777);
}
```
