### ISSUE TITLE
cc-toggle displays extra margin when inside a grid and when inline

### ISSUE THREAD

**Issue by pdesoyres-cc** [CleverCloud/clever-components#896]
When a` <cc-toggle>` with an inlined label is inside a gride area, an extra margin is displayed on top of it.

![image](https://github.com/CleverCloud/clever-components/assets/104012218/2b8d655c-5918-4f87-a93b-e84b40fe3da9)

```html
<div class="grid">
  <div class="area1"><cc-toggle inline legend="legend" choices='[{ "label": "on", "value": "on" },{ "label": "off", "value": "off" }]'></cc-toggle></div>
  <div class="area2">area 2</div>
  <div class="area3">area 3</div>
</div>
```
```css
.grid {
  display: grid;
  grid-template-areas:
            'area1 area3'
            'area2 area3';
  grid-template-columns: 250px 1fr;
  grid-template-rows: max-content 1fr;
  gap: 1em;
}

.area1 {
  grid-area: area1;
  background-color: indianred;
}
.area2 {
  grid-area: area2;
  background-color: steelblue;
}
.area3 {
  grid-area: area3;
  background-color: darkseagreen;
}
```
